### ISSUE TITLE
Request option to whitelist & blacklist roles & classes

### ISSUE THREAD

**Issue by mrbuds** [Vysci/LFG-Bulletin-Board#107]
**Is your feature request related to a problem? Please describe.**

- I'm a healer, i want to see only announce requesting healers =>  filter everything WITHOUT this word
- There are many announce looking for a tank, i'm not interested in groups looking for a tank => filter everything WITH this word

**Describe the solution you'd like**

A list of tristate checkbox (like most weakauras load conditions)
- by roles heal/tank/dps
- by class priest/shaman/mage/etc..........

**Comment by juemrami** [comment]
Closing since this is similar to feature added #205, which lets the user add a global filter to all results. Supports matching multiple simple comma separated patterns. 

eg; searching "healer, priest" will filter for results with both "healer" and "priest" in the message. 
Unfortunately the there is support for logical disjunctions ("or" operations) with patterns atm.
