### ISSUE TITLE
Black Morass recruitment is appearing under the Black Temple section

### ISSUE THREAD

**Issue by raethkcj** [Vysci/LFG-Bulletin-Board#20]
![image](https://user-images.githubusercontent.com/7716908/121225199-e7fc2d80-c84e-11eb-8f2d-72219c3a4e1d.png)

**Comment by Kaaasper** [comment]
This is simply because "black" is a tag for black temple, so "black morass" is picked up. Similarly, "bm" is a german tag for hellfire ramparts, which is also picked up even though my game is in english.

**Comment by shawn571** [comment]
I'm actually seeing BM under Hellfire Ramparts rather than Black Morass. Checked the settings and it clearly says BM should fall under Black Morass but for whatever reason it's not.

![WoWScrnShot_061221_212205](https://user-images.githubusercontent.com/71139409/121792561-9217e480-cbc4-11eb-896b-9664143c8e2c.jpg)
