### ISSUE TITLE
You must press `Close` to save options

### ISSUE THREAD

**Issue by jhaubrich** [Vysci/LFG-Bulletin-Board#200]
**Description**
After making any change to options you must press `Close` in the bottom right hand corner. The changes will not be saved if you click another addon, close by pressing "X" in the top right, close by pressing escape.

**To Reproduce**
1. Click any setting checkbox (e.g. Lock minimap button position)
2. Close config or click away to another config screen
3. Open config. See that Lock minimap button position is unchecked.

**Expected behavior**
Any changes to a config option is expected to remain no matter how you close the window.

**Desktop (please complete the following information):**
 - Version v3.11

**Additional context**
Season of Discovery

**Comment by juemrami** [comment]
Re-opening this issue since the fix in #252 only affected the Dungeon/Raid filter settings panels. 
The custom search patterns tab, for example, still requires a press of the `close` button 
(unless you tab to an expansion's filter tab and then close the settings via any manner to force the implementation of this fix)

**Comment by juemrami** [comment]
Fixed with #277
