### ISSUE TITLE
Add world tour section to raids

### ISSUE THREAD

**Issue by reetarded** [Vysci/LFG-Bulletin-Board#256]
**Describe the solution you'd like**
A section for the raids in cataclysm that is just "world tour" under the raids section. Many raids advertise their runs as world tours and they are missed. Also expand throne of the four winds keywords since I was missing 50% of them with the default words. My current one is "totfw toftw tofw four winds tofw10 towf25 to4w throne tot4w"

**Comment by juemrami** [comment]
Hey,

**Regarding a "World Tour" category**, check out the curseforge alpha/beta, It has support for custom filters and you could make one for world tour. 

![image](https://github.com/Vysci/LFG-Bulletin-Board/assets/20932280/fdfae866-b952-442f-ab41-879d673a3797)

ATM there is no support for complicated search patterns (ie anything more than single words). So you cant match exactly for "world tour" only either "world" or "tour". (see #32)

**As for Totfw**, ill update the tags, thank you. 
Because of the mentioned search pattern limitation i purposefully didnt include "throne" because it would be ambiguous with "Throne of the Tides" for example, and result in false categorizations on the bulletin board.

**Comment by juemrami** [comment]
yea that just a relic of this addon supporting the pre-rdf days. 
When i added support for cata, it would have been weird not to include the dungeons.
I think you should keep "throne" as a custom one for now. Whenever sequence pattern matching is implemented i can see about using less ambiguous patterns.
