### ISSUE TITLE
Custom names doesnt work

### ISSUE THREAD

**Issue by eQuara** [Vysci/LFG-Bulletin-Board#26]
i wanna search "heroic,hc" so i changed karazan to hc and heroic keywords but it doesnt work it looks for karazhan still, all i want is to see "HC"

**Comment by CaptSilverback** [comment]
I just installed this addon and came upon the same issue. Custom words seem to not work at all. Since i play on a german server i spent a few minutes to add the german equivalents to every instance to the find out, that they are not working. Everyone searching for the german equivalents just gets put in the "general"/"Verschiedenes" section on the bottom. Not sure, how it is called in the english config.

**Comment by Krabator** [comment]
I am using the addon and I confirm that the custom keywords are not working.
exemple : in france we use GT2 for "Grotte du temps 2"... i added it as a custom keyword for Black Morass... and it does not works.
