### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by mikkel-ol** [Vysci/LFG-Bulletin-Board#27]
Love the addon, great work.

A couple of suggestions:

* Separate normal and heroic dungeons
* Announcement (play sound, chat message etc.) when someone is looking for you. For instance set it to announce when "dps" or "mage" or "spell cleave" is mentioned on any selected dungeons
* Support space on search patterns. This will allow dungeons like "Black Temple" and "Black Morass" to be properly separated. Patterns could be comma separated instead
* Remove boosts. People selling boosts should not be included in the list (or maybe as an option?). Could be done by searching for "boost" in the string

If you aceept pull requests I might work on it myself.

**Comment by Vysci** [comment]
There is already an announcement feature, if you go to settings you will see an option to announce via sound or chat and even more sub options

I think the black temple or black morass is a small issue atm if it ends up showing up in both (because why are you even filtering for black temple when it’s not in the game). But yes I do plan to add spacing in the future

I’m torn on boosts, on one side people might be legit looking for boosts but on the other side it is annoying when you are not looking at boosts. 

As far as heroic vs non heroic. I agree with that and something I’ll be working on soon

yes I do take pull requests so feel feee to contribute. Note: I don’t tolerate shitty code

**Comment by Vysci** [comment]
Closing this as I have separated these suggestions into individual issues. #31 tracks support for heroics, #32 to track improvement to search patterns

If I misunderstood your announcement comment please open a separate issue for that. 

As far as the boost thing, remember there is a blacklist field in the search patterns, you can add "boost" to the list of blacklisted words (make sure you have custom selected as one of the sources on the top of the search pattern page)
