### ISSUE TITLE
Minimap button never stays in one place

### ISSUE THREAD

**Issue by shenaniganiz0r** [Vysci/LFG-Bulletin-Board#301]
When I move the minimap button to the place I want it to stay and check the "lock the minimap button position" box, it never stays there. Upon re-logging or reloading UI, the button moves, sometimes to random spots. Unchecking the lock button position box yields the same result.

I would like the minimap button to stay in the place that I lock it, it gets tiresome having to move the button every time I log in. I'm running version 1.15.3, and the only other add-on I'm running that modifies the minimap is the Dragonflight UI Classic add-on.

**Comment by juemrami** [comment]
Hey, ill check this out later this weekend. thanks for reporting!

**Comment by juemrami** [comment]
> Dragonflight UI Classic add-on.

Okay, ive downloaded and tested it and look at the Dragonflight UI source. It seems like their Addon was making up for ours not lining up well with `LibDBIcon-1.0` icons because were still not using LibDBIcon (will likely move to it in the future).

The bug is coming from their patch, which overrides the saved positioning values via an early call to the `onUpdate` function during their patch initialization process. This update function relies on your mouse position to determine the location of the button, so thats why it shows up on seemingly random locations, because you mouse is likely never in the same position everytime you reload and their patch runs.

Ive, fixed our button to align better with the other `LibDBIcon-1.0` icons now.

I can disable their patch by changing internal name of our minimap button. I can do that and release it a beta/alpha release on CF for you while i open an issue with them so that they know they can remove their patch 👍

**Comment by shenaniganiz0r** [comment]
Wow, thank you so much for looking into this and giving a detailed response, that's amazing. 🫡

**Comment by juemrami** [comment]
Yea np. Its up on curseforge as `v3.37-beta1` if you wanna play with the fix.
![image](https://github.com/user-attachments/assets/63310355-4436-45d0-aec4-946759bb447b)
Ive got a couple of more fixes to go into the release version of `3.37` so it wont be out soon.

**Comment by shenaniganiz0r** [comment]
Works perfectly, thank you!
