### ISSUE TITLE
Feature Request: Allow exclusion of heroic tag

### ISSUE THREAD

**Issue by Micrologist** [Vysci/LFG-Bulletin-Board#52]
Instead of having a "heroic only filter", I would like to have individual options for including either normal dungeons, heroic dungeons, or both.

**Comment by Vysci** [comment]
You can already filter by heroic dungeons or both normal and heroic (disabling heroic filter shows both), so this is really an ask to also be able to filter by normal dungeon. 

Since there is a visual aid to differentiate between normal and heroic combined with the fact that is a low amount people doing heroics, I don’t think the effort is worth the use case. 

I’ll leave this open in case someone else wants to implement this or if there is a demand for such feature
