### ISSUE TITLE
Variables being displayed instead of Values

### ISSUE THREAD

**Issue by SotelEndlessgg** [Vysci/LFG-Bulletin-Board#93]
![Capture](https://user-images.githubusercontent.com/80719868/123306772-51369e80-d4e7-11eb-9bdb-dad1d8f4424e.PNG)

Reinstall did not alleviate the issue, cropped up when the addon was updated 6/22

Downloaded via WoWUp.io. Running version 2.56.

**Comment by Vysci** [comment]
Can you share what your search pattern setting screen looks like? Same with localization

**Comment by arcane-tl** [comment]
I have this problem too. Version 2.57.

![image](https://user-images.githubusercontent.com/70339038/123412825-b60ef900-d5ba-11eb-95db-138debcc11d3.png)

and the view:

![image](https://user-images.githubusercontent.com/70339038/123413975-033f9a80-d5bc-11eb-821c-ffca0c9ed44f.png)

and some error related:

![image](https://user-images.githubusercontent.com/70339038/123414067-19e5f180-d5bc-11eb-9afb-a96693fff9f7.png)

**Comment by Vysci** [comment]
Ah it looks like there is a conflict with another add on from the looks of it with Attune and/or RClootCouncil. Can you confirm if it works if it’s the only add on running ?

**Comment by SotelEndlessgg** [comment]
Good call on the other addon.

Mine was caused by Titan Panel Classic [Raid Lockout] 
https://www.curseforge.com/wow/addons/titan-panel-classic-raid-lockout

Didn't quite achieve what I was looking for so into the bin it goes.

Thanks for putting out this addon, it's an absolute god send.

**Comment by arcane-tl** [comment]
Yes seems this addon shares some constants/namespace or something like that with a few other addons. Disabling Titan Panel Classic [Raid Lockout] solved this issue for me also but it would be benefitial to find out why and what is causing leakage since I'm getting errors on some other addons as well.

error:
![image](https://user-images.githubusercontent.com/70339038/123483214-0dd74f80-d60f-11eb-91d0-259057afa0e5.png)

**Comment by Vysci** [comment]
Haven't experienced any conflict with TSM. But I am aware there is a rare sorting error that happens but doesn't spam

In general I suggest to just turn off lua errors to everyone (nothing to do with this addon) as it's annoying as hell, by typing
`/console scriptErrors 0`

**Comment by Vysci** [comment]
Closing this as this is a conflict between variable names in two add-ons. Since Lua sucks as it defaults variables to be global this is bound to happen. In future when I noticed things are global without needing to be I will make appropriate updates to limit the scope but not going to actively figure out what conflicts with what add-on and who is not accessing the correct data
